/*

  E-GIZMO IR SPEED SENSOR MODULE
  SAMPLE CODE
  
  THIS SKETCH IS TO GET THE MOTOR/DYNAMO SPEED
  DETECTING, PULSE COUNTING BY READING THE DIGITAL
  AND ANALOG OUTPUT FOR SENSITIVITY VALUE. TO DISPLAY
  THE OUTPUT DATA ON THE SERIAL MONITOR.

 CODES BY E-GIZMO MECHATRONIX CENTRAL
 http://www.e-gizmo.com
 MARCH 9, 2017

 */

// DIGITAL PIN
int DIGITAL_OUT= 2;

void setup() {
  //INITIALIZE SERIAL COMMUNICATION BAUD RATE
  Serial.begin(9600);
  //MAKE THE DIGITAL PIN'S INPUT
  pinMode(DIGITAL_OUT, INPUT);
}

void loop() {
  
  // READ THE INPUT PIN
  int DIGITAL_VALUE = digitalRead(DIGITAL_OUT);
  int SENSITIVITY = analogRead(A0);
  
  // PRINT OUT THE READ VALUE:
  Serial.print(SENSITIVITY);
  Serial.print(" ");
  Serial.println(DIGITAL_VALUE);
  
  delay(1);        // DELAY IN BETWEEN READS FOR STABILITY
}




